### PR TITLE
Implemented the shuffle feature

### PR DESCRIPTION
**Pull request by vchrombie**
Solves Issue #12 
The shuffle feature is implemented in the player.js
As requested, the next song will be played randomly from current playlist, without changing the displayed order.

Implemented the code in both playNext() and playPrev() functions.
Let me know if anything is wrong.

### CODE REVIEW

**Comment by udiboy1209** [comment]
This is slightly different from what we had discussed. Notice that in your current implementation, it is possible that the next song is same as the current song because of the random function. Or that only a few songs are played more frequently than others.

What we would want is that the entire playlist is played, but in a "random" order. You can generate this fixed-but-random order when you start shuffle, and change it once you loop through it.

**Comment by vchrombie** [comment]
Yeah it is possible that the next song is same as the current song.

So, I have to generate a temporary random order in which the videos have to be played whenever the shuffle is ON.
Each time you ON the shuffle, a new order should be generated.

Is that right?

**Comment by udiboy1209** [comment]
@vchrombie yes, that's correct. Also, a new order should be generated in two other cases:

 1. When all songs are played once i.e. you run through the entire shuffled order.
 2. When user specifically selects to play a song from the playlist (by clicking).

**Comment by vchrombie** [comment]
Okay 
I will work on that implementation.

**Comment by udiboy1209** [comment]
This PR looks abandoned, so closing this.

**Pull request closed without merging**
